#### This first part imports the pandas library and reads in the CSV file.

In [2]:
import pandas as pd
df = pd.read_csv('/Users/aanikaschueler/Desktop/Beiwe/download_summary_statistics.csv')
df.head()

,Date,Participant Id,Study Id,Timezone,Accelerometer Bytes,Ambient Audio Bytes,App Log Bytes,Bluetooth Bytes,Calls Bytes,Devicemotion Bytes,...,Uniq Individual Call Or Text Count,Total Surveys,Total Completed Surveys,Total Opened Surveys,Average Time To Submit,Average Time To Open,Average Duration,Walking Time,Steps,Cadence
0,2025-12-04,443yroib,XXb2Gm78TVBGesqyd6oPjjXQ,EST,11138880.0,NaN,NaN,NaN,NaN,6628463.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-12-05,443yroib,XXb2Gm78TVBGesqyd6oPjjXQ,EST,18976998.0,NaN,NaN,NaN,NaN,10597511.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-12-06,443yroib,XXb2Gm78TVBGesqyd6oPjjXQ,EST,7903340.0,NaN,NaN,NaN,NaN,7308099.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-12-07,443yroib,XXb2Gm78TVBGesqyd6oPjjXQ,EST,11576525.0,NaN,NaN,NaN,NaN,6660137.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-12-08,443yroib,XXb2Gm78TVBGesqyd6oPjjXQ,EST,17279511.0,NaN,NaN,NaN,NaN,12661063.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### First, we want to get the unique count of Participant IDs.

In [6]:
df["Participant Id"].nunique()

28

#### Next, we will create a table. We will have a row for each participant and the following columns: 1) Participant ID. 2) First date data was uploaded. 3) Last date data was uploaded. 4) Total number of days GPS data was collected. 5) Average daily GPS data volume. 6) Total number of days Accelerometer data was collected. 7) Average daily Accelerometer data volume.

In [16]:
summary = (
    df.groupby("Participant Id", as_index=False)
    .agg(
        first_date_uploaded=("Date", "min"),
        last_date_uploaded=("Date", "max"),
        total_GPS_days=("Gps Bytes", lambda x: (x > 0).sum()),
        avg_daily_GPS_volume=("Gps Bytes", lambda x: round(x.loc[x > 0].mean(),3)),
        total_accelerometer_days=("Accelerometer Bytes", lambda x: (x > 0).sum()),
        avg_daily_accelerometer_volume=("Accelerometer Bytes", lambda x: round(x.loc[x > 0].mean(),3))
    )
)
summary.head()

,Participant Id,first_date_uploaded,last_date_uploaded,total_GPS_days,avg_daily_GPS_volume,total_accelerometer_days,avg_daily_accelerometer_volume
0,443yroib,2025-12-04,2025-12-11,8,37925.125,8,1.246384e+07
1,555gcdo6,2025-04-08,2025-06-18,71,59117.113,72,1.744188e+07
2,6a4s9uln,2025-08-11,2025-10-19,70,349420.329,70,6.483083e+07
3,7evdij49,2025-09-18,2025-11-04,48,94672.021,48,2.450423e+07
4,832rlsvt,2025-08-28,2025-10-10,44,542595.227,44,6.708945e+07